default_platform(:android)

ENV['NODE_ENV'] = 'production'

platform :android do
  desc 'Upload a new version'
  lane :upload do
    upload_to_server(
      endPoint: ENV['SERVER_URL'],
      multipartPayload: {
        :fileFormFieldName => 'file'
      }
    )
  end

  desc 'Deploy a new version'
  lane :deploy do
    gradle(task: 'clean app:assembleRelease', project_dir: 'android')
    upload
  end
end

platform :web do
  desc 'Upload a new version'
  lane :upload do
    sftp_upload(
      server_url: ENV['SFTP_HOST'],
      server_user: ENV['SFTP_USER'],
      server_key: "#{Dir.home}/.ssh/id_rsa",
      target_dir: ENV['SFTP_TARGET'],
      file_paths:["web/dist"],
    )
  end

  desc 'Deploy a new version'
  lane :deploy do
    yarn(
      command: "build",
      package_path: "./web/package.json"
    )
    upload
  end
end
