default_platform(:android)

platform :android do
  desc 'Upload a new version'
  lane :upload do
    upload_to_server(
      endPoint: ENV['SERVER_URL'],
      multipartPayload: {
        :fileFormFieldName => 'file'
      }
    )
  end

  desc 'Deploy a new version'
  lane :deploy do
    gradle(task: 'clean app:assembleRelease', project_dir: 'android')
    upload
  end
end
